# Generated by Django 4.2 on 2024-02-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRevenue',
        ),
    ]
