# Generated by Django 4.2 on 2024-02-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_delete_customerrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_source', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custommer_revenues', related_query_name='customer_revenue', to='customer.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Revenues',
                'unique_together': {('customer', 'revenue_source')},
            },
        ),
    ]
